import deadpoolPoster from '../assets/deadpool.jpg';
import jokerPoster from '../assets/joker.jpg';
import dunePoster from '../assets/dune.jpg';
import venomPoster from '../assets/venom.jpg';
import insideOutPoster from '../assets/insideout2.jpg';
import garfieldPoster from '../assets/garfield.jpg';
import alienRomulusPoster from '../assets/alien.jpg';
import godzillaKongPoster from '../assets/godzilla.jpg';
import ifPoster from '../assets/if.jpg';
import planetApesPoster from '../assets/kindom.jpg';
import misionPoster from '../assets/mision.jpg';
import barbiePoster from '../assets/barbie.jpg';
import marioPoster from '../assets/mario.jpg';
import transformersPoster from '../assets/transformers.jpg';
import wonkaPoster from '../assets/wonka.jpg';
import jurassicPoster from '../assets/jurassic.jpg';
import moonGirlPoster from '../assets/moon.jpg';
import animalesPoster from '../assets/animales.jpg';
import mercyPoster from '../assets/mercy.jpg';
import shelterPoster from '../assets/shelter.jpg';
import soulm8tePoster from '../assets/soul8mate.jpg';
import projectHailPoster from '../assets/hailmary.jpg';
import alphaPoster from '../assets/alpha.jpg';
import readyOrNotPoster from '../assets/ready.jpg';


export const peliculasData = [
  { id:"deadpool-wolverine", titulo:"Deadpool & Wolverine", categoria:"acción", año:2024, poster:deadpoolPoster, duracion:"2h 10m", descripcion:"Deadpool se cruza con Wolverine en un encuentro que cambia el curso del multiverso y los obliga a trabajar juntos aunque se detesten profundamente. A medida que atraviesan realidades alternativas descubren que un enemigo oculto está alterando la línea temporal para destruirlos y borrar su existencia. Entre caos, humor descontrolado y peleas explosivas, ambos deberán aceptar que su destino depende de confiar el uno en el otro. Esta alianza imposible se convertirá en una batalla épica donde cada decisión puede definir el futuro de todos los mundos." },
  { id:"joker-folie-a-deux", titulo:"Joker: Folie à Deux", categoria:"drama", año:2024, poster: jokerPoster, duracion:"2h 12m", descripcion:"Arthur Fleck intenta encontrar sentido en un mundo que continúa empujándolo hacia la violencia y la deshumanización. Mientras su fama crece sin intención real, Gotham se hunde cada vez más en la miseria, el caos social y la búsqueda desesperada de identidad colectiva. En este nuevo capítulo Arthur se enfrenta a su propio reflejo emocional, donde la mente se convierte en un escenario tan peligroso como las calles que lo rodean. La línea entre realidad y alucinación se difumina por completo mientras su leyenda empieza a tomar forma definitiva." },
  { id:"dune-parte-dos", titulo:"Dune: Parte Dos", categoria:"ciencia ficción", año:2024, poster:dunePoster, duracion:"2h 35m", descripcion:"Paul Atreides continúa su ascenso como figura clave del destino de Arrakis mientras las alianzas políticas se tensan y los imperios chocan sin piedad. Su vínculo con los Fremen se fortalece en una lucha que va más allá de la arena y las profecías, buscando cambiar el sistema de poder galáctico por completo. En medio de batallas colosales, traiciones silenciosas y visiones del futuro que pueden ser devastadoras, Paul deberá elegir entre cumplir el destino que otros quieren imponerle o crear el suyo propio. Esta guerra definirá el equilibrio del universo para siempre." },
  { id:"venom-the-last-dance", titulo:"Venom: The Last Dance", categoria:"acción", año:2024, poster:venomPoster, duracion:"1h 55m", descripcion:"Eddie y Venom enfrentan el mayor desafío hasta ahora cuando fuerzas superiores comienzan a cazar symbiotes con intenciones desconocidas. La relación entre ambos se vuelve más intensa que nunca mientras descubren secretos sobre el origen de su vínculo y el riesgo que implica para el planeta. En su huida deberán decidir si salvarse a sí mismos o luchar contra quienes buscan utilizar su poder para destruir todo. El destino de su conexión definirá el rumbo final de esta historia marcada por caos, humor y furia incontrolable." },
  { id:"inside-out-2", titulo:"Inside Out 2", categoria:"animación", año:2024, poster: insideOutPoster, duracion:"1h 45m", descripcion:"Riley enfrenta un nuevo capítulo de crecimiento cuando sus emociones descubren sentimientos completamente nuevos que ponen a prueba su equilibrio interno. La adolescencia trae inseguridades, miedos desconocidos y decisiones que parecen gigantes, lo que abre un viaje emocional tan caótico como conmovedor. Las emociones deberán aprender a convivir, reorganizarse y evolucionar para guiar a Riley en un mundo más complejo que nunca. Esta aventura explora la madurez, la identidad y la importancia de aceptar lo que sentimos incluso cuando nos asusta." },
  { id:"the-garfield-movie", titulo:"The Garfield Movie", categoria:"comedia", año:2024, poster:garfieldPoster, duracion:"1h 40m", descripcion:"Garfield se ve obligado a salir de su vida cómoda y llena de buena comida cuando un imprevisto lo lleva a una aventura que nunca habría elegido por voluntad propia. En este viaje inesperado deberá enfrentarse a la acción, al esfuerzo físico y a situaciones que pondrán a prueba su flojera legendaria. Entre risas, caos y momentos tiernos, Garfield descubrirá que incluso él puede convertirse en héroe cuando la situación lo exige. A veces salir de la zona de confort puede cambiar la forma de ver el mundo para siempre." },
  { id:"alien-romulus", titulo:"Alien: Romulus", categoria:"terror", año:2024, poster:alienRomulusPoster, duracion:"2h 05m", descripcion:"Una tripulación joven se adentra en una estación espacial abandonada sin conocer la amenaza biológica que se oculta en sus pasillos. Lo que comienza como una misión de exploración se transforma rápidamente en una pesadilla cuando descubren una criatura que evoluciona con una agresividad imparable. En total aislamiento deberán luchar por sobrevivir mientras la paranoia destruye la confianza entre ellos. El horror regresa a su esencia más brutal donde cada rincón oscuro puede ser el último que vean con vida." },
  { id:"godzilla-vs-kong-new-empire", titulo:"Godzilla x Kong: The New Empire", categoria:"acción", año:2024, poster:godzillaKongPoster, duracion:"2h 20m", descripcion:"Godzilla y Kong deberán unir fuerzas cuando un antiguo poder oculto emerge desde lo profundo y amenaza la supervivencia de la humanidad entera. Los titanes, a pesar de su rivalidad histórica, se enfrentan a una entidad que supera todo lo que el mundo conocía. Esta alianza imposible desencadena batallas colosales que transformarán paisajes, ciudades y la historia misma del planeta. El destino de la Tierra dependerá de que dos fuerzas que nunca debieron coexistir logren pelear del mismo lado." },
  { id:"if-2024", titulo:"IF", categoria:"animación", año:2024, poster:ifPoster, duracion:"1h 50m", descripcion:"Una niña descubre que los amigos imaginarios que las personas olvidan siguen existiendo en un mundo paralelo lleno de color, magia y emoción. Su conexión con este universo la lleva a intentar reunirlos con sus dueños reales, sin comprender los riesgos emocionales que eso implica. A medida que avanza deberá enfrentar decisiones que ponen en juego la alegría, la nostalgia y la memoria afectiva de toda una generación. IF es una aventura emotiva donde la imaginación se convierte en la clave para sanar y reconectar con lo que creíamos perdido." },
  { id:"kingdom-of-the-planet-of-the-apes", titulo:"Kingdom of the Planet of the Apes", categoria:"ciencia ficción", año:2024, poster:planetApesPoster, duracion:"2h 25m", descripcion:"Generaciones después del reinado de Caesar, los simios dominan el planeta mientras los humanos sobreviven en pequeños grupos casi olvidados. Un nuevo líder simio intenta imponer una visión totalitaria y redefinir el orden social, poniendo en riesgo la paz lograda. Un joven simio deberá emprender un viaje para descubrir la verdad sobre su historia y el origen de la humanidad. Su decisión final puede cambiar el equilibrio entre especies y el destino del mundo entero." },
  { id:"mision-imposible-sentencia-final", titulo:"Misión Imposible: Sentencia Final", categoria:"acción", año:2025, poster:misionPoster, duracion:"2h 30m", descripcion:"Ethan Hunt tendrá que enfrentar una amenaza global que utiliza la manipulación, la infiltración y la desinformación para destruir alianzas enteras desde las sombras. Cada movimiento puede desencadenar consecuencias irreversibles, obligándolo a tomar decisiones límite donde nada es lo que parece. Las traiciones, la tensión constante y la acción extrema llevan esta misión al punto más peligroso de su carrera. Esta vez salvar el mundo implica asumir un precio altísimo que podría cambiarlo para siempre." },
  { id:"barbie-la-pelicula", titulo:"Barbie", categoria:"comedia", año:2024, poster:barbiePoster, duracion:"1h 54m", descripcion:"Barbie vive en un mundo perfecto y colorido donde todo parece estar bajo control hasta que una crisis existencial la obliga a cuestionarse qué significa realmente ser ella misma. Su viaje la llevará fuera de lo conocido para descubrir que el mundo real puede ser tan complejo como fascinante. Entre humor, autocrítica y emoción, Barbie descubre que la identidad va más allá de un molde perfecto. Esta aventura celebra la autenticidad y la capacidad de reinventarse sin límites." },
  { id:"super-mario-bros-la-pelicula", titulo:"Super Mario Bros: La Película", categoria:"animación", año:2024, poster:marioPoster, duracion:"1h 48m", descripcion:"Mario y Luigi son transportados accidentalmente a un reino lleno de criaturas, magia y peligro donde deberán enfrentar al villano más temido del lugar. Su misión será salvar el Reino Champiñón antes de que sea dominado por completo y la esperanza desaparezca. En este viaje descubrirán habilidades que nunca imaginaron y vínculos que trascienden mundos. Una aventura que combina nostalgia, acción y humor para una generación que creció con este universo." },
  { id:"transformers-rise-of-the-beasts", titulo:"Transformers: Rise of The Beasts", categoria:"acción", año:2025, poster:transformersPoster, duracion:"2h 20m", descripcion:"Una nueva facción de Transformers llega a la Tierra con tecnología y poderes nunca antes vistos, alterando el equilibrio entre Autobots y Decepticons. Humanos y máquinas deberán trabajar juntos para enfrentar una amenaza que puede acabar con todo. La guerra evoluciona hacia un nivel más intenso donde las lealtades se pondrán a prueba y los héroes surgirán de los lugares más inesperados. Esta batalla definirá quién merecerá controlar el destino del planeta." },
  { id:"wonka-la-pelicula", titulo:"Wonka: La Película", categoria:"aventura", año:2024, poster:wonkaPoster, duracion:"1h 55m", descripcion:"Antes de convertirse en el genio del chocolate, un joven inventor decide perseguir un sueño que pocos creen posible. Su talento, imaginación y capacidad para sorprender al mundo lo llevarán a desafiar poderosos intereses y sistemas tradicionales. En esta aventura fantástica conocemos el origen de una de las mentes más creativas de todos los tiempos. Una historia inspiradora sobre cómo los sueños se vuelven reales cuando se decide romper las reglas." },
  { id:"mundo-jurassico-renacer", titulo:"Mundo Jurásico: Renacer", categoria:"acción", año:2025, poster:jurassicPoster, duracion:"2h 20m", descripcion:"Después de que los dinosaurios recuperaran territorio, la humanidad se ve obligada a convivir con criaturas imponentes que no pertenecen a su tiempo. La supervivencia se vuelve una lucha constante entre adaptación y resistencia. Nuevas especies desconocidas emergen con comportamientos impredecibles, desatando caos en zonas controladas. El futuro dependerá de descubrir cómo coexistir sin desencadenar la extinción definitiva." },
  { id:"marvels-moon-girl-and-devil-dinosaur", titulo:"Marvel’s Moon Girl and Devil Dinosaur", categoria:"animación", año:2025, poster:moonGirlPoster, duracion:"1h 50m", descripcion:"Moon Girl utiliza su inteligencia extraordinaria para combatir el crimen junto a su enorme dinosaurio compañero. Juntos se enfrentan a villanos que amenazan la ciudad con planes extravagantes y peligrosos. Esta dupla única demuestra que las diferencias pueden ser la mayor fortaleza. Una aventura llena de acción, misterio y energía juvenil donde la imaginación se convierte en arma principal." },
  { id:"animales-fantasticos-secretos-de-dumbledore", titulo:"Animales Fantásticos: Secretos de Dumbledore ", categoria:"aventura", año:2025, poster:animalesPoster, duracion:"2h 20m", descripcion:"El mundo mágico enfrenta nuevas conspiraciones que ponen en juego la estabilidad entre magos y muggles. Newt Scamander deberá liderar una misión que podría cambiar el rumbo del poder dentro del universo mágico. Entre criaturas extraordinarias, conflictos políticos y descubrimientos ocultos, la verdad detrás de viejos secretos sale a la luz. Esta entrega eleva el conflicto hacia una batalla decisiva por el futuro de la magia." },

  // Estrenos 2026
  { id:"mercy-2026", titulo:"Mercy", categoria:"ciencia ficción", año:2026, poster:mercyPoster , duracion:"2h 10m", descripcion:"Un experimento científico destinado a expandir las fronteras del conocimiento desencadena una amenaza que supera toda lógica humana. Mientras la realidad se altera, la humanidad lucha contra un fenómeno cósmico imparable que desafía la comprensión. La carrera contra el tiempo se vuelve desesperada cuando la frontera entre vida y destrucción comienza a desmoronarse. La pregunta ya no es cómo detenerlo, sino si existe alguna posibilidad de sobrevivir." },
  { id:"shelter-2026", titulo:"Shelter", categoria:"acción", año:2026, poster:shelterPoster, duracion:"1h 55m", descripcion:"En un mundo devastado por conflictos globales, un protector misterioso se convierte en la última defensa de una ciudad acorralada por fuerzas externas. Su misión lo obliga a enfrentarse a enemigos que operan desde las sombras con recursos ilimitados. Cada batalla se vuelve más intensa mientras intenta evitar la caída total del único lugar que aún ofrece refugio. La resistencia será el último pilar para mantener viva la esperanza." },
  { id:"soulm8te-2026", titulo:"SOULM8TE", categoria:"terror", año:2026, poster:soulm8tePoster, duracion:"2h 00m", descripcion:"Un nuevo sistema social virtual se vuelve viral prometiendo conexión emocional absoluta entre usuarios. Lo que nadie sabe es que detrás de la plataforma se oculta una presencia oscura que se alimenta de quienes participan. A medida que la red crece, fenómenos inexplicables comienzan a manifestarse en la vida real. La tecnología se convierte en un canal para el horror, llevando a los protagonistas a luchar por su propia cordura." },
  { id:"project-hail-mary-2026", titulo:"Project Hail Mary", categoria:"ciencia ficción", año:2026, poster:projectHailPoster, duracion:"2h 20m", descripcion:"Un astronauta despierta solo en una nave sin recordar cómo llegó allí y descubre que la humanidad depende de él para evitar una extinción global. Mientras reconstruye su memoria debe resolver un enigma científico que podría salvar el planeta. En el aislamiento del espacio deberá enfrentar tanto el vacío físico como el emocional. Su misión será encontrar una respuesta antes de que sea demasiado tarde para todos." },
  { id:"alpha-2025", titulo:"Alpha", categoria:"acción", año:2026, poster:alphaPoster, duracion:"2h 10m", descripcion:"Una agente de elite se infiltra en una red internacional que controla información y armas avanzadas en secreto. Cada paso la lleva más cerca de descubrir una conspiración capaz de alterar el equilibrio global. Su habilidad e inteligencia serán puestas al límite cuando las traiciones comienzan a surgir. Esta misión redefine hasta dónde está dispuesta a llegar para evitar una catástrofe mundial." },
  { id:"ready-or-not-2-2026", titulo:"Ready or Not 2", categoria:"terror", año:2026, poster:readyOrNotPoster, duracion:"1h 50m", descripcion:"Grace intenta comenzar una nueva vida, pero el pasado vuelve de la forma más cruel cuando es arrastrada a un nuevo juego mortal. Esta vez la escala del peligro se expande y las reglas evolucionan hacia una experiencia más perturbadora e impredecible. La oscuridad vuelve a acecharla mientras lucha por sobrevivir en un entorno donde nadie es lo que parece. El horror se intensifica llevando este juego sangriento a límites nunca antes vistos." }
];
